#Priglasheniya insert append
my_guests = ['Egor', 'Lesha', 'Sasha']
print(my_guests)
print('Hello ' + my_guests[0] + ' go drink a beer !!')
print('Hello ' + my_guests[1] + ' go drink a beer !!')
print('Hello ' + my_guests[2] + ' go drink a beer !!')
print('Саша не смог прийти так как у него коробка виндовс')
my_guests[2] = 'Oleg'
print(my_guests)
print('Hello ' + my_guests[0] + ' go drink a beer !!')
print('Hello ' + my_guests[1] + ' go drink a beer !!')
print('Hello ' + my_guests[2] + ' go drink a beer !!')
print('К нам еще придут люди')
my_guests.insert(2, 'Slava')
my_guests.insert(0, 'Alesya')
my_guests.append('Andrey')
print(my_guests)
print('Hello ' + my_guests[0] + ' go drink a beer !!!')
print('Hello ' + my_guests[2] + ' go drink a beer !!!')
print('Hello ' + my_guests[3] + ' go drink a beer !!!')
print('Hello ' + my_guests[4] + ' go drink a beer !!!')
print('Hello ' + my_guests[5] + ' go drink a beer !!!')